class_name PlayGamesCatalog
extends RefCounted

## The one place that knows which Play Console achievement each Numblop achievement is.
##
## Pure data and pure lookups: no plugin, no network, no autoload state. The ids are generated by
## Play Console when the achievements are created there and are opaque — they encode nothing and
## cannot be derived from the local id, so this table is the only way across.
##
## It sits in `scripts/autoload/` rather than beside the other catalogs in `scripts/app/` because
## everything under `scripts/app/` is forbidden from mentioning Play at all, and a test enforces
## that. This is not an autoload; it is a class that belongs on the Play side of that wall.
##
## `tests/state/test_play_games_catalog.gd` fails if `AchievementCatalog` grows an achievement this
## table does not know, which is what stops a new achievement from silently never reaching Play.

## Numblop achievement id -> Play Console achievement id.
##
## Console names one of these differently from the catalog: its "Shoe collection" is the local
## `collection_footwear`.
const ACHIEVEMENT_IDS: Dictionary = {
    "first_steps": "CgkIuuOoyNMdEAIQBQ",
    "streak_10": "CgkIuuOoyNMdEAIQAw",
    "streak_20": "CgkIuuOoyNMdEAIQDg",
    "streak_50": "CgkIuuOoyNMdEAIQGQ",
    "streak_100": "CgkIuuOoyNMdEAIQBg",
    "streak_500": "CgkIuuOoyNMdEAIQCQ",
    "streak_1000": "CgkIuuOoyNMdEAIQBw",
    "experience_500": "CgkIuuOoyNMdEAIQEA",
    "experience_1000": "CgkIuuOoyNMdEAIQEg",
    "experience_5000": "CgkIuuOoyNMdEAIQCA",
    "experience_10000": "CgkIuuOoyNMdEAIQFA",
    "collection_body_color": "CgkIuuOoyNMdEAIQFg",
    "collection_belly_color": "CgkIuuOoyNMdEAIQDA",
    "collection_hat": "CgkIuuOoyNMdEAIQFQ",
    "collection_glasses": "CgkIuuOoyNMdEAIQCg",
    "collection_necklace": "CgkIuuOoyNMdEAIQDw",
    "collection_footwear": "CgkIuuOoyNMdEAIQGA",
    "island_2": "CgkIuuOoyNMdEAIQAQ",
    "island_3": "CgkIuuOoyNMdEAIQFw",
    "island_4": "CgkIuuOoyNMdEAIQDQ",
    "island_5": "CgkIuuOoyNMdEAIQAg",
    "island_6": "CgkIuuOoyNMdEAIQEw",
    "island_7": "CgkIuuOoyNMdEAIQCw",
    "island_8": "CgkIuuOoyNMdEAIQBA",
    "island_9": "CgkIuuOoyNMdEAIQEQ",
}


## The Play id for a local achievement, or an empty string when there is none.
##
## An unmapped achievement is skipped rather than raised: a build that adds an achievement before
## it exists in Console must still play, and the test above is what stops that from shipping.
static func achievement_id(local_id: String) -> String:
    var mapped: Variant = ACHIEVEMENT_IDS.get(local_id, "")
    return mapped if mapped is String else ""


static func has_achievement(local_id: String) -> bool:
    return not achievement_id(local_id).is_empty()
